opt:
  train:
    w_bg: False
    num_workers: 8
    batch_size: 1
    start: 0
    end:  1500
    skip: 4
    downscale: 1
    
  val:
    w_bg: False
    num_workers: 8
    batch_size: 1
    start: 180  
    end: 180  
    skip: 1
    downscale: 1
  test:
    w_bg: True
    num_workers: 8
    batch_size: 1
    start: 1500 
    end: 1799 
    skip: 1
    downscale: 1
    audio_driven: False
    cross_identity: False
    identity: Fah
